# Generated by Django 3.2.9 on 2021-12-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0002_bookofmonth_description'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='book_club_subscriptions_next_month',
            field=models.ManyToManyField(related_name='users_subscribed_next_month', to='book_clubs.BookOfMonth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='book_club_subscriptions_this_month',
            field=models.ManyToManyField(related_name='users_subscribed_this_month', to='book_clubs.BookOfMonth'),
        ),
    ]
