# Generated by Django 3.2.9 on 2021-12-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0002_bookofmonth_description'),
        ('profiles', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='book_club_subscriptions_next_month',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_subscribed_next_month', to='book_clubs.BookOfMonth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='book_club_subscriptions_this_month',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_subscribed_this_month', to='book_clubs.BookOfMonth'),
        ),
    ]
