# Generated by Django 3.2.9 on 2021-12-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_currently_on_sale'),
        ('profiles', '0006_auto_20211224_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='book_club_subscriptions_this_month',
            field=models.ManyToManyField(blank=True, null=True, related_name='owned_by', to='products.Product'),
        ),
    ]
