# Generated by Django 3.2.9 on 2021-12-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0002_bookofmonth_description'),
        ('products', '0018_remove_product_currently_on_sale'),
        ('profiles', '0007_alter_userprofile_book_club_subscriptions_this_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owned_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='owned_by', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='book_club_subscriptions_this_month',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_subscribed_this_month', to='book_clubs.BookOfMonth'),
        ),
    ]
