# Generated by Django 3.2.9 on 2021-12-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofile_first_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscriptions_in_bag',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
