# Generated by Django 3.2.9 on 2021-12-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_currently_on_sale'),
        ('checkout', '0006_alter_order_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineItem',
            new_name='OrderLineItemProduct',
        ),
        migrations.CreateModel(
            name='OrderLineItemSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
