# Generated by Django 3.2.9 on 2021-12-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0002_bookofmonth_description'),
        ('checkout', '0007_auto_20211220_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitemsubscription',
            name='product',
        ),
        migrations.AddField(
            model_name='orderlineitemsubscription',
            name='book_of_month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_clubs.bookofmonth'),
            preserve_default=False,
        ),
    ]
