# Generated by Django 3.2.9 on 2021-12-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_currently_on_sale'),
        ('checkout', '0008_auto_20211220_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitemsubscription',
            name='book_of_month',
        ),
        migrations.AddField(
            model_name='orderlineitemsubscription',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
