# Generated by Django 3.2.9 on 2021-12-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20211226_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitemsubscription',
            old_name='Product',
            new_name='product',
        ),
    ]
