# Generated by Django 3.2.9 on 2021-12-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0003_bookofmonth_price'),
        ('checkout', '0010_rename_product_orderlineitemsubscription_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitemsubscription',
            name='product',
        ),
        migrations.AddField(
            model_name='orderlineitemsubscription',
            name='book_of_month',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='book_clubs.bookofmonth'),
            preserve_default=False,
        ),
    ]
