# Generated by Django 3.2.9 on 2021-12-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookofmonth',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
