# Generated by Django 3.2.9 on 2021-12-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0002_bookofmonth_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookofmonth',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
