# Generated by Django 3.2.9 on 2021-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book_of_month',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='currently_on_sale',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
