# Generated by Django 3.2.9 on 2021-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FilePathField(blank=True, null=True, path='media/pdfs'),
        ),
    ]
