# Generated by Django 3.2.9 on 2021-12-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_book_of_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='book_of_month',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_of_month', to='products.product'),
        ),
    ]
