# Generated by Django 3.2.9 on 2021-12-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_delete_bookofmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book_of_month',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='BookOfMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Book of Month',
            },
        ),
    ]
