# Generated by Django 3.2.9 on 2021-12-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211215_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookOfMonth',
        ),
    ]
