# Generated by Django 3.2.9 on 2021-12-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_delete_bookofmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='wider_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.widercategory'),
        ),
    ]
