# Generated by Django 3.2.9 on 2021-12-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_widercategory_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currently_on_sale',
        ),
    ]
